from decimal import Decimal
from typing import Any, Iterable, Self

class Money:
    def __init__(self, amount: Self | Decimal | str | float) -> None: ...
    @property
    def amount(self) -> Decimal: ...
    def round(self, n: int) -> Self: ...
    def round_up(self, n: int) -> Self: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> float: ...
    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self | Decimal: ...
    def __neg__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Self) -> bool: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    def for_json(self) -> str: ...

def sum_(elems: Iterable[Money | None]) -> Money: ...

class MoneyWithVAT:
    def __init__(
        self,
        net: Self | Decimal | str | float | None,
        tax: Self | Decimal | str | float | None,
    ) -> None: ...
    @property
    def net(self) -> Money: ...
    @property
    def tax(self) -> Money: ...
    @property
    def gross(self) -> Money: ...
    @property
    def tax_rate(self) -> Decimal: ...
    @property
    def tax_rate_for_display(self) -> Decimal: ...
    @property
    def is_positive(self) -> bool: ...
    @property
    def is_negative(self) -> bool: ...
    def is_equal_up_to_cents(self, other: Self) -> bool: ...
    def is_lower_up_to_cents(self, other: Self) -> bool: ...
    def is_lower_or_equal_up_to_cents(self, other: Self) -> bool: ...
    def rounded_to_cents(self) -> Self: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: Self) -> Self: ...
    def __sub__(self, other: Self) -> Self: ...
    def __mul__(self, other: Iterable[Self | None]) -> Self: ...
    def __rmul__(self, other: Iterable[Self | None]) -> Self: ...
    def __truediv__(self, other: float) -> Self: ...
    def __neg__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Self) -> bool: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    @staticmethod
    def max(*args: object) -> Self | None: ...
    @staticmethod
    def ratio(dividend: Self, divisor: Self) -> MoneyWithVATRatio: ...
    @staticmethod
    def safe_ratio(
        dividend: Self | None, divisor: Self | None
    ) -> MoneyWithVATRatio | None: ...
    @staticmethod
    def safe_ratio_decimal(
        dividend: Self | None,
        divisor: Decimal,
    ) -> MoneyWithVATRatio | None: ...
    @staticmethod
    def fast_sum(iterable: Iterable[Self | None]) -> Self: ...
    @staticmethod
    def fast_sum_with_none(iterable: Iterable[Self | None]) -> Self | None: ...
    def for_json(self) -> dict: ...
    @staticmethod
    def from_json(dict: dict) -> Self: ...

class MoneyWithVATRatio:
    def __init__(self, net_ratio: Decimal, gross_ratio: Decimal) -> None: ...
    @property
    def net_ratio(self) -> Decimal: ...
    @property
    def gross_ratio(self) -> Decimal: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __mul__(self, other: Decimal) -> Self: ...
    def __eq__(self, other: Self) -> bool: ...
    def for_json(self) -> dict: ...
